[package]
name = "gui"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
strum = { version = "0.28", features = ["derive"] }
domain = { path = "../domain" }
index = { path = "../index" }
io-map = { path = "../io-map" }
io-config = { path = "../io-config" }
io-fonts = { path = "../io-fonts" }
io-vcs = { path = "../io-vcs" }
io-comments = { path = "../io-comments" }
io-lsp = { path = "../io-lsp" }
cli = { path = "../cli" }
features = { path = "../features" }
ui = { path = "../ui" }
platform = { path = "../platform" }
regex = "1"

[lints]
workspace = true
