[workspace]
members = ["crates/*", "xtask"]
resolver = "3"

[workspace.lints.rust]
unsafe_code = "deny"
unreachable_pub = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
must_use_candidate = "allow"
module_name_repetitions = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
allow_attributes = "deny"
allow_attributes_without_reason = "deny"
indexing_slicing = "deny"
string_slice = "deny"
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
dbg_macro = "deny"
print_stdout = "deny"
print_stderr = "deny"
str_to_string = "deny"
iter_over_hash_type = "deny"
absolute_paths = "deny"
clone_on_ref_ptr = "deny"
get_unwrap = "deny"
map_err_ignore = "deny"
let_underscore_must_use = "deny"
if_then_some_else_none = "deny"
shadow_unrelated = "deny"
min_ident_chars = "deny"
mod_module_files = "deny"
rc_buffer = "deny"
empty_structs_with_brackets = "deny"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
