[package]
name = "codemap-next"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "codemap-next"
path = "src/main.rs"

[dependencies]
cli = { path = "../cli" }
gui = { path = "../gui" }
domain = { path = "../domain" }
index = { path = "../index" }
io-map = { path = "../io-map" }

[lints]
workspace = true
