[package]
name = "codemap"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "codemap"
path = "src/main.rs"

[dependencies]
strum = { version = "0.28", features = ["derive"] }
cli = { path = "../cli" }
gui = { path = "../gui" }
domain = { path = "../domain" }
index = { path = "../index" }
io-map = { path = "../io-map" }
io-comments = { path = "../io-comments" }

[dev-dependencies]
features = { path = "../features" }

[lints]
workspace = true
