[package]
name = "cli"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
strum = { version = "0.28", features = ["derive"] }
domain = { path = "../domain" }
index = { path = "../index" }
io-map = { path = "../io-map" }
io-vcs = { path = "../io-vcs" }
features = { path = "../features" }
clap = { version = "4", default-features = false, features = ["std", "derive", "help", "usage", "error-context", "suggestions"] }
regex = "1"

[lints]
workspace = true
