[package]
name = "index"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
domain = { path = "../domain" }
io-source = { path = "../io-source" }
io-cache = { path = "../io-cache" }
io-lsp = { path = "../io-lsp" }
tree-sitter = "0.25"
tree-sitter-rust = "0.24"
tree-sitter-odin = "1"
tree-sitter-c = "0.24"
tree-sitter-python = "0.25"
tree-sitter-javascript = "0.25"
tree-sitter-typescript = "0.23"

[lints]
workspace = true
